// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "panel/questions"
import "panel/answers"
import "panel/home/card_users"
import "panel/home/card_subjects"
import "panel/home/card_user_answers"
import "panel/home/card_user_progress"
import "panel/zip_code"
